### ISSUE TITLE
NODE_BLOOM flag

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#10]
Bitcoin rejected this change, litecoin has kept it - relook at whether we should keep it or not.
Suggest we drop it *unless* any of the mobile wallets use it.

**Comment by Waterloodown** [comment]
I would say read the following first post made here. 
http://bitcoin-development.narkive.com/jjxAgi2B/bitcoin-development-node-bloom-service-bit

Might be worth keeping for now and deprecate later. We can discuss this point.

**Comment by cydg** [comment]
Does not look like bloom filters is something we want.

**Comment by mjmacleod** [comment]
Bloom filters we might want, but the NODE_BLOOM flag is not really needed for that, supporting it is going to be a pain, and bitcoin support bloom filters without it... So I suggest we get rid of it, but must make sure we don't break any NLG services somehow in the process (doubtful)

**Comment by mjmacleod** [comment]
Removing for now we can add back if it becomes apparent that we need it, but we shouldn't bitcoin gets by just fine without it.
