### ISSUE TITLE
(Bitcoin 0.10) Standard script rules relaxed for P2SH addresses

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#13]
Look into this and decide whether its appropriate or not for gulden.

**Comment by Waterloodown** [comment]
IsStandard rules relaxed for P2SH addresses: Bitcoin Core nodes will now happily relay nearly all P2SH redemption scripts. This opens up a whole new world of possibilities for creative scripts such as complicated multisig, hash-locked oracle addresses, etc. See here for the rationale and more info.
https://gist.github.com/gavinandresen/88be40c141bc67acb247

Will be worth adding for future use. imo

**Comment by cydg** [comment]
Not sure if we need the relaxed rules right now. The stricter rules might be enough for now and we can switch on the relaxed ones if there is some demand for it.

**Comment by mjmacleod** [comment]
As discussed at last meeting, lets just go ahead and catch up with bitcoin here.
