### ISSUE TITLE
NODE_GETUTXO

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#16]
// NODE_GETUTXO means the node is capable of responding to the getutxo protocol request.
// Bitcoin Core does not support this but a patch set called Bitcoin XT does.
// See BIP 64 for details on how this is implemented.

I think this should be off by default, ensure we turn it off by default.

**Comment by Waterloodown** [comment]
Agreed on turning off, we can relook at turning it on in the future if there is a need.

**Comment by cydg** [comment]
Better to turn it off.

**Comment by mjmacleod** [comment]
It appears that it is currently turned off, we must just watch for this one in future merges if they enable it, I'm not sure I'm a huge fan of the idea but time will tell...
