### ISSUE TITLE
Fix for GetBlockValue() after block 13,440,000 (BIP42)

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#18]
Look into this for gulden.

**Comment by Waterloodown** [comment]
You can read the comments below.
https://github.com/bitcoin/bitcoin/issues/3776
https://bitcointalk.org/index.php?topic=130614.msg1399528#msg1399528

I would just fix it for gulden even it won't be a issue for another 60 odd years.

**Comment by cydg** [comment]
while the block number is still far ahead for NLG, it is more of a cleanup of that code part to prevent the potentila problem. So yes, we should take it.

**Comment by mjmacleod** [comment]
Ahh, it is just because they continuously use a bitshift trick to halve the block reward, so eventually it will overflow.
This will no longer be an issue if we dump the halving scheme.
