### ISSUE TITLE
(Bitcoin 0.9.2) Lower paytxfee warning threshold from 0.25 BTC to 0.01 BTC

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#19]
Look into this for gulden.

**Comment by Waterloodown** [comment]
This was brought about for the value of bitcoin rising and meaning 0.01 is a substantial enough fee amount. 
This definitely needs to be a personalized setting and doesn't need to be changed for us at this point.

**Comment by cydg** [comment]
From my point of view: Let's keep it at the old NLG values as long as there is no real reason to change it.
