### ISSUE TITLE
setmininput

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#2]
Either:

1) Verify that this still works.
2) Consider removing it as it is a litecoin specific thing and not part of bitcoin code, so consider if its actually worth keeping.

**Comment by Waterloodown** [comment]
setmininput - <amount> is a real and is rounded to the nearest 0.00000001 (litecoin API call) , most likely not worth keeping as I don't believe any service for guldencoin is using this feature.
For bitcoin settxfee is the comnbination of setmininput and settxfee that litecoin which appear to be the same calls.

**Comment by cydg** [comment]
Can cause more confusion than good. So let's get rid of it
