### ISSUE TITLE
(Bitcoin 0.9) OP_RETURN

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#20]
Look into this and whether this is something we want in Guldencoin or not - probably yes but worth double checking.

**Comment by Waterloodown** [comment]
Frank was excited about this function and can be used along with multisig(contract) setups. I agree to add.

**Comment by cydg** [comment]
I see some possible use cases, so I vote for it. Might need an additional saveguard to prevent abuse.

**Comment by mjmacleod** [comment]
Okay seems there is no reason to leave this out then, lets go ahead with it.
