### ISSUE TITLE
(Bitcoin 0.9) Increase default -blockmaxsize/prioritysize to 750K/50K

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#21]
Look into for gulden.

**Comment by Waterloodown** [comment]
I would have a read through this article. Not needed for gulden at this stage but might be worth changing now for future mining transaction usage.

http://hashingit.com/analysis/39-the-myth-of-the-megabyte-bitcoin-block

**Comment by cydg** [comment]
Keep it at NLG values. Why increase it w/o any need? There hasn't been any probs with the block size we have. We can carefully increase our block size when we come to a point where we really need it

**Comment by mjmacleod** [comment]
It seems we should just keep the default values here.
