### ISSUE TITLE
getwork, getworkex

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#3]
Either:

1) Ensure these still work.
2) Consider dropping them - they were deprecated/removed from bitcoin itself.

**Comment by Waterloodown** [comment]
getwork , getworkex [data, coinbase] is being deprecated by Litecoin in the future according to their main dev Warren.
getblocktemplate is the call to be used instead of the above for bitcoin.

**Comment by cydg** [comment]
Agreed, we want to modernize the code base and not keep carrying older stuff with us for ages w/o reason.
As long as noone has a good argument why we still need them ...

**Comment by mjmacleod** [comment]
Removed it for now, if anyone comes up with a good reason we can put it back.
