### ISSUE TITLE
maxsigcachesize

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#4]
Guldencoin has 9924 maxsigcachesize.
Bitcoin has 50000.

It is not clear *why* this change was made or if it was necessary (or a mistake?) must look at this closer.

**Comment by Waterloodown** [comment]
Litecoin/Dash also use 50 000, Limit size of signature cache to <n> entries (default: 50000) is basically what the function is used for. I say we switch this up to 50 000 for consistency.

**Comment by cydg** [comment]
another search$replace case it looks like
