### ISSUE TITLE
MAX_INV_SZ

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#6]
Bitcoin has MAX_INV_SZ 50000
Guldencoin has 9924.

Check if this change is actually necessary or if it is e.g. some search/replace bug or something - it seems odd that these two values keep coming up for different things.

**Comment by Waterloodown** [comment]
I don't believe it is needed as we not generating the throughput required, however in 8 years from now it will be a different story. I say we up the value to 50000 for consistency sake or we will keep getting these differences coming up.

**Comment by cydg** [comment]
Maximum number of entries in an "inv" protocol message = 9924? How got that calculated?
Let's get it straigth now and be done with it

**Comment by mjmacleod** [comment]
From the protocol documentation:

"inv Allows a node to advertise its knowledge of one or more objects. It can be received unsolicited, or in reply to getblocks.
Payload (maximum 50,000 entries, which is just over 1.8 megabytes):"

Litecoin has it as 50000, I doubt there is a good reason for it not to be?
Unless someone can provide a good reason I suggest we do what everyone else has done here.
