### ISSUE TITLE
nFileVersion check in walletdb.cpp

### ISSUE THREAD

**Issue by mjmacleod** [nlgcoin/guldencoin2#7]
Bitcoin checks for 50000
Guldencoin checks for 9924.

Check if this change is actually necessary - it doesn't look like it - or if it is e.g. some search/replace bug or something - it seems odd that these two values keep coming up for different things.

**Comment by Waterloodown** [comment]
As per other comments, It's not necessary at this stage but we should change it this time while this update is our focus.

**Comment by cydg** [comment]
yep, looks like a search&replace thing.
Let's get it straigth now and be done with it
